42ity/fty-core

- Makefile.am
- configure.ac
- src/agents/configure_inform/configure_inform.cc
- src/agents/inventory/fty-inventory.cc
- src/warranty/warranty-metric.cc
> PROBLEM: Repository naming is not updated

- .gitignore
- configure.ac
- tools/git_details.sh
- tools/tntnet.xml
Solution: Delete libbiosproto from configure.ac; add missing files.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: Make in top directory of fty-core fails.

- Makefile.am
- setup/20-fty-compat.sh
- systemd/legacy-asset.service.in
> Problem: legacy-asset does not have systemd file

- obs/preinstallimage-bios.sh
Solution: drop the old code, enable everything with fty-*
> Problem: generating of image fail on removed services

- Makefile.am
> Problem: core still try to build catch

- systemd/ipc-meta-setup.service.in
> Problem: service contains incorrect path to ipc-meta-setup script

- setup/20-fty-compat.sh
> Problem: incorrect command used

- systemd/legacy-asset.service.in
Solution: correct name of the service
> Problem: legacy-asset cannot find tntnet@bios

- docs/examples/update-rc3.d/05-image-arch.conf
- docs/examples/update-rc3.d/10-image-os-location.etn.conf
- docs/examples/update-rc3.d/30-image-uboot.etn.conf
- tests/CI/ci-reset-virtual-machine.sh
- tests/CI/ci-setup-test-machine.sh
- tests/CI/restapi-request.sh
- tools/update-rc3
Solution: cherry-pick + add correct metadata to all of them
> Problem: some patches pushed to the old core after split

- obs/preinstallimage-bios.sh
- tools/db-init.in
Solution: find a substring in IMGTYPE
> Problem: perl not on devel image

- tools/diagnostic-information
Solution: call mysqldump as well
> Problem: there's no DB dump in diagnostic script

- obs/preinstallimage-bios.sh
> Problem: Typo in creaing link, missing fty-res move

- Makefile.am
Follow-up to https://github.com/42ity/fty-core/pull/46
> Makefile.am : fix dist/clean of setup/20-th-names.sh

- tools/db-init.in
Solution: move the asset name to extended attribute "name" if does not
already exists
> Problem: display name is going to be stored in ext now

- obs/preinstallimage-bios.sh
Solution: use -p parameter correctly
> Problem: image build fail

- tools/update-rc3
> Problems: update-rc3 can be made friendlier to admins

- obs/preinstallimage-bios.sh
- setup/20-fty-compat.sh
- systemd/bios-agent-inventory.service.in
- systemd/bios-db-init.service.in
- systemd/bios-fake-th.service.in
- systemd/bios-reset-button.service.in
- systemd/biostimer-warranty-metric.service.in
- systemd/ifplug-dhcp-autoconf.service.in
- tools/diagnostic-information
Solution: apply a couple of fixes
> Problem: diagnostic script is broken. Standardize on FTY systemd service template. Improve ipc-meta mvln().

- tools/update-rc3
>  Problem: want a standard procedure to finish OEM setup

- tools/systemctl
>  Problem: systemctl does not allow our new components

- tools/update-rc3
Make life easier when we want to skip updating and use other facilities
> update-rc3 : alias "--no-download-images" as "-N"

- database/mysql/location_topology.sql
> Problem: group contains nonexisting type

- setup/20-fty-compat.sh
> Problem: can't accept license after upgrade 

- docs/examples/sudoers.d/fty_00_base.in
> PROBLEM: www-data can't run /bin/systemctl

- obs/preinstallimage-bios.sh
Solution: read the credentials from the file
> Problem: web can't access DB on a second boot

- setup/20-fty-compat.sh
> Problem: state file name missing

- tools/db-init.in
Solution: make directories readable by www-data group
> Problem: license accept fails

- tools/db-init.in
Solution: call it on /var/lib ...
> Problem: chgrp called on wrong file

- systemd/fty-db-init.service.in
Solution: use correct alias name
> Problem: can't start fty-metric-store

- Makefile.am
- systemd/fty-db-init.service.in
- systemd/fty-db-upgrade.service.in
- tools/start-db-services
> Problem: need to enable and start db depentent services

- docs/examples/sudoers.d/fty_00_base.in
> Problem: duplicate definition in fty_00_base.in

- .gitignore
- Makefile.am
>  Problem: distcheck fails because of tools/start-db-services

- Makefile.am
Solution: make it more readable and extensible
> Problem: 42-bios-systemd.preset generation wants refactoring

- systemd/fty-db-firstboot.service.in
Solution: don't enable it through bios.target
> Problem: DB created during boot

- docs/examples/sudoers.d/fty_00_base.in
Solution: open it back in sudoers setup, for now...
> Problem: www-data currently needs real /bin/systemctl

- obs/preinstallimage-bios.sh
> Problem: mysql started because of multi-level.target

- setup/20-fty-compat.sh
- setup/ipc-meta-setup.sh
Solution:  situation when file is not present handled
> Problem: setup script tries to access nonexisting file

- systemd/fty-db-engine.service.in
- tools/start-db-services.in
> Problem: typos in recent fixes

- docs/examples/sudoers.d/fty_00_base.in
Solution: add ip route to sudoers
> Problem: admin user needs to manipulate with routing table

- tools/update-rc3
Solution: detail the message a bit more
> Problem: warning about IMAGE_URL vs IMGTYPE inconsistency is not easy to understand

- setup/20-fty-compat.sh
- tools/db-init.in
Solution: address currently identified problems
> Problem: issues updating from older release

- database/mysql/load_data.sql
- database/mysql/location_topology.sql
- database/mysql/power_topology.sql
Solution: update with their variants from CI tests, so they correspond to current data schema again
> Problem: SQL files with test data are outdated

- tools/fty-route
Solution: add fty-route command, which manipulates with interfaces file
using autgtool (like REST API).
This is WIP script, but better on gh that on my laptop
> Problem: need to maintain routing info from cli script

- Makefile.am
- docs/examples/sudoers.d/fty_00_base.in
- tools/fty-route
> Problem: need to manipulate with routing table

- tools/update-rc3
Solution: only report it was asked to reboot after successful downloads if it really was; otherwise just report a success
> Problem: update-rc3 says it was asked to reboot in any case

- tools/generate-release-details.sh
> Problem: hwd part number is missing

- Makefile.am
- setup/15-dpkg-database.everytime.sh
- setup/ipc-meta-setup.sh
First shot at solution to cover the easy common cases.
> Problem: Fix pkgdb update

- setup/15-dpkg-database.everytime.sh
> Problem: 15-dpkg-database.everytime.sh needs support of RW_ROOT

- obs/preinstallimage-bios.sh
> Problem : mdns protocol requests are DROPPED by FW

- setup/20-fty-compat.sh
SOLUTION: Do it.
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>
> PROBLEM: Need to "move" uptime manually

- database/mysql/0009_device_type_extension.sql
Solution: new subtype sensorgpio added
> Problem: We need new device subtype in database

- obs/preinstallimage-bios.sh
> Problem: Need a GPIO group

- tools/update-rc3
> [BIOS-3771]Problem : we want to skip bb detection after oem-finish

- tools/tntnet-ExecStartPre.sh.in
Solution: provide the hardware generated UUID value (if any) to the webserver environment
> Problem: feedback email sends random UUID

- database/mysql/0010_super_parent_names.sql
Solution: fixed column reference
> Problem: invalid column reference in CREATE VIEW

- .travis.yml
> Problem: Travis default OS is now Ubuntu Trusty (14)

- database/mysql/0010_super_parent_names.sql
Solution: Added up to 10 levels of parentage
> Problem: It is difficult to extend system parentage

- tools/tntnet-ExecStartPre.sh.in
Solution: add it to tntnet preexec (others may use such files too)
> Problem: want to know OS virtualization status via env

- systemd/fty-envvars.service.in
Solution: Change it.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: Oneshot service must have Restart=no.

- obs/preinstallimage-bios.sh
Solution: Add it to the SASL group
> Problem: Need to broaden bios privileges

- obs/preinstallimage-bios.sh
- tests/CI/ci-reset-virtual-machine.sh
- tools/rc-bios-ci-container-delayedstart
Solution: clean up the image during build; fix typos.
> Problem: OBS metadata in final image, typos in CI scripts

- database/mysql/0011_default_rc.sql
Solution: Set RC-0 power source only to it's parent.
> Problem: RC-0 adds itself as it's own power source

- database/mysql/0011_default_rc.sql
Solution: fixed read only attributes for RC-0
> Problem: some attributes should be read only

- database/mysql/0012_device_type_extension.sql
- database/mysql/Makefile.am
> Problem: we need new subtype 'gpo'

- Jenkinsfile
- tests/CI/ci-reset-virtual-machine.sh
- tools/update-rc3
* ci-reset-virtual-machine.sh creates RO overlay roots under "rootfs" dir as in https://github.com/42ity/fty-core/pull/190
* ci-reset-virtual-machine.sh always wipes container contents https://github.com/42ity/fty-core/pull/191
* Add Forceflash support to update-rc3 as in https://github.com/42ity/fty-core/pull/192
* A bit of Jenkinsfile restructuring
> Functional updates to 1.3 from master branch

- docs/examples/pam.d/fty
- docs/examples/pam.d/fty-password
- obs/preinstallimage-bios.sh
> First step for compatibility with Convergence User Management

- obs/preinstallimage-bios.sh
> Split 10_common_basic.xml to separate static and auth parts

- obs/preinstallimage-bios.sh
Solution: Generate the config snippet into the correct location
Follow-up to fix the fallout from #205
> Problem: Houston, we lost web logins!

- docs/examples/rsyslog.d/10-ipc.conf.in
- tests/CI/ci-reset-virtual-machine.sh
- tests/CI/ci-setup-test-machine.sh
- tests/CI/jenkins-reset-virtuals.groovy
- tests/CI/resetdb-bios-rc-demo.sh
- tests/CI/update_demo
- tools/loghost-rsyslog
Also try to better make sure database only starts after confirmed acceptance of EULA. UPDATE: The DB part specifically was already handled by PR #214 now.
> Update helper scripts in 1.3 from master

- obs/preinstallimage-bios.sh
Solution: Do it.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: We want to mask/disable interop services.

- obs/preinstallimage-bios.sh
OBS failed to generate an image
> Problem : tntnet.xml.example has moved

- tools/generate-release-details.sh
We can do that from inside the image easily.
> Fetch the hardware data from SMBIOS on x86_64

- Makefile.am
- database/mysql/0013_user_management.sql
- database/mysql/Makefile.am
- obs/preinstallimage-bios.sh
- tools/Makefile.am
- tools/generate-release-details.sh
- tools/generate_env_user4sql.sh
- tools/udhcpc-hook.sh
In the script (0013_user_management.sql) All uids are hard coded! because the following code does not work !!!!
SET @admin_uid := \! id -u admin;
> Add user management tables

- Makefile.am
- tools/systemctl
Solution: commented out for now
> Problem: we currently don't have warranty-metric

- obs/preinstallimage-bios.sh
Solution: try to do explicit systemctl preset later.
> Problem: preset-all sets enables service that should be disabled

- obs/preinstallimage-bios.sh
Solution: sdded comments to better explain preset for ova-welcome-screen
> Problem: preset not easy to understand without looking into preset file

- obs/preinstallimage-bios.sh
Create a log configuration file with debug level for devel image, info otherwise.
This file define the logging level of the root logger and use a default Console appender
> Problem : Need to generate the log configuration file on image

- obs/preinstallimage-bios.sh
> Problem: on tntnet, Json and token extraction must be first calls

- Makefile.am
- configure.ac
These seem to be remnants of the now separate fty-rest library.
> Cleanup the configure script and Makefile

- tools/diagnostic-information
> Problem : web audit logs are not exported by the diagnostic tool

- systemd/bios.service
Add a comment to avoid the surprise I had looking at my year-old code ;)
> bios.service : explain the systemd dependencies

- docs/examples/Makefile.am
- docs/examples/ftylog.d/10-ftylog.cfg
- obs/preinstallimage-bios.sh.in
Signed-off-by: Millieret, Xavier <XavierMillieret@Eaton.com>
> Adding config files ftylog

- tools/generate-release-details.sh
Now that the x86_64 initramfs also takes care of providing a UUID, this
logic is no longer needed. This reverts these two commits:
6d6289366d2d ("generate-release-details: Generate a v4 UUID on VMware")
363cc8fca889 ("generate-release-details: Only generate the v4 UUID during first boot")
> generate-release-details: Revert the v4 UUID logic

- Makefile.am
- systemd/fty-license-accepted.service
- tools/disable-root-account
- tools/enable-root-account
> Add the disable/enable root account scripts

- tools/disable-root-account
- tools/enable-root-account
> Arm ROOT password

- tools/update-rc.d.sh
> [DO NOT MERGE 1.4.1]Problem : disabling ntp service restart it

- docs/examples/Makefile.am
- docs/examples/ftylog.d/10-ftylog.cfg
- docs/examples/ftylog.d/20-wwwlog.cfg
- obs/preinstallimage-bios.sh.in
We will fix the right access issue  to www-audit.log
> Problem : we have to separe web servlet log appenders from bios backend daemond

- tools/systemctl
Solution: add to filter in systemctl/journalctl wrapper
> Problem: new NUT service and target units not allowed

- obs/preinstallimage-bios.sh.in
(cherry picked from commit 862fd325d9fddfa66b0b96cd730a8c206cdf6f82)
> Problem : etn-graphite.cfg is not writable by www-data user

- tools/db-init.in
> Problem : DB schema is not exported

- systemd/ipc-meta-setup.service.in
for now, I didn't remove 10-avahi-lxc.sh setup script as he has no effect.
If someone complains, I can do it :)
> Problem : avahi does not belong to bios.target anymore

- tools/update-rc3.in
Solution: Try to retrieve it, part of the image file
The manifest is also deleted upon image removal
> Problem: Need to handle image manifest too

- tools/update-rc3.in
Solution: Create /var/lib/fty/sw-update
> Problem: Directory may not exist

- tools/update-rc3.in
Solution: Do it
The new name is <image squashfs filename>-manifest.json
> Problem: Need to rename single-image manifest file

- tools/diagnostic-information
Solution: set log level to warning, using env var
> Problem: CSV export are polluted with tntnet debug

- database/mysql/0015_ipm2.sql
- database/mysql/Makefile.am
> IPM2 requests DB improvements

- tools/diagnostic-information
Solution: Add automation audit logs
> Problem: Need to complete logs in diagnostic archive

- tools/diagnostic-information
Solution: Fix the path to get log files
> Problem: Karag log file are in KARAF_LOG not /var/log

- tools/diagnostic-information
> Karaf logs - collect diags into separate directory

- docs/examples/update-rc3.d/10-image-os-location.etn.conf
- tools/update-rc3.in
> update-rc3.in / 10-image-os-location.etn.conf : fix quoting of OSIMAGE_DISTRO

- tools/generate-release-details.sh
Thanks to @jana-rapava for noticing the bug (recently added by me).
> Fix imgtype in release details and subsequently generated files

- tools/udhcpc-hook.sh
Solution: make the service manipulation more reliable by parameterizing
> Problem: udhcpc-hook.sh checks for service "ntpd" and manipulates "ntp"

- systemd/fty-db-engine.service.in
Solution: do not use curly braces
> Problem: systemd mangled shell script in fty-db-engine.service.in

- Makefile.am
- configure.ac
- obs/preinstallimage-bios.sh.in
- systemd/fty-hostname-setup.service.in
- tools/fty-hostname-setup
- tools/udhcpc-hook.sh
- tools/udhcpc-override.sh
The OS image side of the solution for "localhost" appearing in the DNS.
> Backport 2.0.0 hostname

- docs/examples/ftylog.d/20-wwwlog.cfg
Solution: Fix it
* wwwlog syslog appender
> Problem: www-audit logs (tntnet) are not persisted by journald (syslog compatibility)

- systemd/fty-tntnet@.service.in
Signed-off-by: Xavier Millieret <XavierMillieret@eaton.com>
> FIxing issue on tntnet starting

- obs/preinstallimage-bios.sh.in
> Problem: PQSWMBT-3713 - improve devel image deployment - firewall - add tcp port 5005 

- tools/systemctl
- tools/update-rc3.in
Part of fix to CI fallout due to #382
> systemctl : allow to manage fty-hostname-setup service

- obs/preinstallimage-bios.sh.in
Signed-off-by: Xavier Millieret <XavierMillieret@eaton.com>
> Force the user admin to change this passwd at the first logging

- systemd/biostimer-verify-fs.timer
- tools/systemctl
- tools/update-rc3.in
- tools/verify-fs.in
Signed-off-by: Clement Perrette <clementperrette@eaton.com>
> Update checksum result log and recursive

- obs/preinstallimage-bios.sh.in
Solution: Condition nut-server and license-accepted
> Problem: OVA welcome screen is flooded

- obs/preinstallimage-bios.sh.in
> 2nd attempt to fix meta cyclic deps

- obs/preinstallimage-bios.sh.in
> Backport 2nd attempt to fix meta cyclic deps to 2.1.0

- tools/verify-fs.in
Signed-off-by: Clement Perrette <clementperrette@eaton.com>
> Add verification of signature (2.1.0)

- systemd/fty-db-engine.service.in
- tools/start-db-services.in
Proposed backport of #413 for release
> Hotfix DB service startup occasionally failing after EULA (2.1.0)

- Makefile.am
- setup/91-logrotate-fty.sh
- systemd/fty-logrotate.service
- systemd/fty-logrotate.timer
- systemd/ipc-meta-setup.service.in
- tools/systemctl
> Backport 2.1.0 logging

- obs/preinstallimage-bios.sh.in
> Problem:  tcp port 1099 access required on devel image (master), PQSWMBT-3828

- Makefile.am
- obs/preinstallimage-bios.sh.in
- systemd/fty-monitor-unlock.service
> Lock monitor (2.1.0)

- obs/preinstallimage-bios.sh.in
> obs/preinstallimage-bios.sh.in : fix database to localhost… (master)

- obs/preinstallimage-bios.sh.in
> # Limit SSH to Administrator user

- obs/preinstallimage-bios.sh.in
> Limit SSH to Administrator user (further fix)

- obs/preinstallimage-bios.sh.in
> Problem: featureimage/powerchain-analysis

- database/mysql/0015_composite_power_system.sql
- database/mysql/Makefile.am
* 0015_composite_power_system.sql
> PQSWMBT-4163 - new 'cops' asset, new 'pcu' device

- database/mysql/0021_device_type_extension.sql
- database/mysql/Makefile.am
* 0021_device_type_extension.sql
> Fix 0015_xxx.sql

- database/mysql/0019_device_type_extension.sql
- database/mysql/Makefile.am
* pass script index from 0021 to 0019
> Problem: sql init scripts concurrency with emc4j 'fall' script

- obs/preinstallimage-bios.sh.in
- tools/rcmysql-transient
- declarations of cops asset and pcu device
> integration of Featureimage/powerchain analysis

- docs/examples/sudoers.d/fty_00_base.in
Needed by https://github.com/42ity/fty-srr/pull/33
> Remove fty-srr user from main sudoers file

- tools/Makefile.am
- tools/license-agreement.sh
> PQSWMBT-4598 - EULA acceptance CLI

- images/devel-pkg.list
- images/runtime-pkg.list
- obs/preinstallimage-bios.sh.in
- tests/CI/ci-reset-virtual-machine.sh
Prospect fix for [PQSWPRG-7893], not much tested yet. Snippets delivered in the preinstall here were tried in different generations of our OS images, all have their quirks now worked-around. But the image generation on OBS with these changes was not attempted yet.
> Switch preconfig from iptables to nftables

- Makefile.am
- obs/preinstallimage-bios.sh.in
- setup/02-migrate-users-bios-script.sh
- setup/02-migrate-users.sh
See https://bitbucket-prod.tcc.etn.com/projects/BIOS/repos/ipc-accounts/pull-requests/16 for details.
> Create _bios-script user with system UID

- tests/CI/weblib.sh
* fix: handle /etn/v1/oauth2/token uri (usm2)
> IPMVAL-2889 - fix usm2 compatibility (weblib.sh::_api_get_token)

- tools/get-ssl-cert.sh
- tools/tntnet-ExecStartPre.sh.in
> Update certficate update scripts

- tools/Makefile.am
> Update list of tools to deliver in the final image

- tools/get-ssl-cert.sh
Adding error checking, log-tracing, a few simplifications...
> get-ssl-cert.sh: make more robust

- tools/bios-networking
> Update bios-networking (2.3.1)

- docs/examples/ftylog.d/10-ftylog.cfg
* ftylog.cfg: fix inherited loglevel
> ftylog.cfg: fix inherited loglevel

- obs/preinstallimage-bios.sh.in
> Make the packages list filename more generic

- tests/CI/ci-reset-virtual-machine.sh
Impacts only local containers on developer systems
> [IPMPROG-440] ci-reset-virtual-machine.sh: support OSIMAGE_FILENAME-manifest.json

- database/mysql/0025_device_type_extension.sql
* 0025_device_type_extension.sql, add actuator
> add actuator decl. in sql scripts

- obs/preinstallimage-bios.sh.in
Same comments apply as in #531 and #532. Accepting this change as a quick fix, but hoping for the better change coming soon.
> Fix issue, the setup was in the wrong file [master]

- tools/JSON.sh
- tools/systemctl
Important one is the fix for systemctl wrapper to not fail on find'ing stuff in new FS layouts for systemd in Debian 11
> Port updates from master to 2.4.0

- database/mysql/0026_measurement_value_i64.sql
- database/mysql/Makefile.am
> fix sql filename length 0026
