src/web/src/alert_list.ecpp, src/web/src/asset_GET.ecpp
SUB-PROBLEM: Need to rename alert_list, asset_GET
SOLUTION: Rename it
Does not include rename of
- systemctl rappers/services/timers etc...
- configuration/state files etc...
`autoreconf -fiv && ./configure && make` works
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>
=> PROBLEM: Repository naming is not updated

obs/preinstallimage-bios.sh
Solution: create compat symlinks, so both old and new paths will be
valid
=> Problem: paths changes due renaming

tools/systemctl
Solution: allow everything with fty- prefix
=> Problem: systemctl wrapper do not understand fty units

Makefile.am, setup/20-fty-compat.sh, setup/ipc-meta-setup.sh, systemd/ipc-meta-setup.service.in
Solution: add a script which will move and link back the file, so system
will just works in all cases
=> Problem: New daemons use new config file location

obs/preinstallimage-bios.sh
When path is renamed there is no backward compatibility in case of
upgrade of old system
SOLUTION: Add specific dir links
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>
=> PROBLEM: No backward compatibility

tools/systemctl
SOLUTION: Fix to bios-db-init
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>
=> PROBLEM: Typo in bios-db-int

systemd/bios-ssh-last-resort.service.in
Solution: create missing /var/run/sshd in ExecStart
=> Problem: sshd does not start in container

systemd/bios-agent-autoconfig.service.in, systemd/bios-agent-inventory.service.in
Solution: Fix the naming.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
=> Problem: Systemd services try to run nonexisting executables.

setup/20-fty-compat.sh, tools/systemctl
Solution: remove code handling FTY variable
=> Problem: systemctl wrapper does not work

obs/preinstallimage-bios.sh
Solution: pass configuration file to each call of systemd-tmpfiles
=> Problem: tmpfiles weren't created

systemd/bios-agent-inventory.service.in
Solution: change service file to dummy one
=> Problem: bios-agent-inventory is expected by CI scripts

tools/systemctl
Solution: move it to right place
=> Problem: systemctl is refusing to handle fty-metrict-composite units

obs/preinstallimage-bios.sh
Solution: move everithing to share/bios to share/fty and make link bios -> fty
=> Problem: Image won't build because unexpected paths

obs/preinstallimage-bios.sh
Solution: move also fty-core to fty
=> Problem: Still wrong path fty-core

obs/preinstallimage-bios.sh
Solution: move to libexec/fty, create links instead bios and fty-core
=> Problem: wrong path in libexec

obs/preinstallimage-bios.sh
Solution: create link to libexec/fty
=> Problem: bios directory doesn't exist in libexec

tools/bios-networking
Solution: kill dhcp client in bios-networking script
=> Problem: network interfaces use DHCP all the time

tools/bios-networking
=> Problem: bios-networking: bad operator for string comparsion

.gitignore, Makefile.am, docs/examples/Makefile.am, docs/examples/rules.d/90-ipc-persistent-th.rules, obs/preinstallimage-bios.sh, setup/20-th-names.sh.in
Solution: create compat symlinks to real tty devices + fix compatiblity
with HW rev 00
=> Problem: we want to use TH1-TH4 in port names still

Makefile.am
Solution: Add it to Makefile.am to be installed
=> Problem: Scrip ipc-meta-setup.sh is missing in package

tools/systemctl
Solution: consider the "activating" units as failed (e.g. mysql or nut-driver instances that are trying to start up for long enough to get caught in this state).
````
root@validation-rc1:~# /tmp/systemctl  list-ipm-units --failed > /tmp/f2 2>&1
root@validation-rc1:~# systemctl  list-ipm-units --failed > /tmp/f1 2>&1
diff -bu /tmp/froot@validation-rc1:~# diff -bu /tmp/f?
--- /tmp/f1     2017-03-09 12:30:06.830574826 +0000
+++ /tmp/f2     2017-03-09 12:29:58.075576045 +0000
@@ -8,6 +8,23 @@
fty-metric-store-cleaner.service
fty-metric-store.service
fty-metric-tpower.service
+mysql.service
+nut-driver@5PX1500-01.service
+nut-driver@9PX-BiosU1.service
+nut-driver@9PX-BiosU4.service
+nut-driver@BladeUPS.service
+nut-driver@ROZ.UPS14.service
+nut-driver@ROZ.UPS33.service …
```
=> Problem: systemctl list-ipm-units "--not-active" or "--failed" glosses over units that are "activating" forever

obs/preinstallimage-bios.sh
Solution: in obs/preinstallimage-bios.sh, use relative symlinks for remapped files (bios - fty); link fty.cfg to bios.cfg (not bios); also comment the difference between "bios" and "bios.cfg" files
=> Problem: absolute paths in symlinks complicate management of chroots

obs/fty-core.dsc, tools/generate-release-details.sh
Solution: add the uuid program to package requirements, and support to generate the UUID from HWD details when updating the data files
=> Problem: we want Device UUID available in release-details.json (for fty-info)

tools/generate-release-details.sh
Solution : rename "hardware-uuid" to "uuid"
=> Problem: hardware-uuid label is too retrictive to hardware

tools/generate-release-details.sh
Solution: Use 42ITy as default and add more variables
=> Problem: Release info and UUID are tied to Eaton

tools/generate-release-details.sh
Reverts 42ity/fty-core#56
As detailed in my comment to the original PR #56, this particular string identifies the hardware unit the best we can, for a certain definition of what "hardware" means at all (either way, a unique instance of the 42ity environment). A generic "uuid" will lose meaning very quickly, as we begin to identify more and more of other meaningful aspects of the system, and will just be ambiguous.
=> Revert "Problem: hardware-uuid label is too retrictive to hardware"

tools/generate-release-details.sh
Reverts #57 to restore #56
While I personally don't quite agree with this choice of naming, for the reasons I posted in comments to those earlier PRs, the CTC tribe hath spoken, and they choose how projects would interact.
CCing @aquette @jana-rapava @geraldguillaume @thalman to ultimately take into account the chosen `"uuid"` instead of `"hardware-uuid"` key name in the `release-details.json` file and `sysinfo` REST API and the data for `fty-info` and other progs and scripts that interact with this.
=> Revert "Revert "Problem: hardware-uuid label is too retrictive to hardware""

obs/preinstallimage-bios.sh
Solution: Create symlink from legacy installations' metric-composite to new dedicated fty-sensor-env path
Coupled with https://github.com/42ity/fty-sensor-env/pull/12
=> Problem: fty-sensor-env depends on fty-metric-composite to store files

obs/preinstallimage-bios.sh
Solution: change script to install the tmpfiles configs into OS standard location
See also the proposed fix for OBS
=> Problem: systemd standard says there is no /usr/lib/SYSTEMD/tmpfiles.d/

obs/preinstallimage-bios.sh
Context: Dir `/var/lib/fty/fty-sensor-env/` is pre-created by packaging now, so the symlink made later becomes
`/var/lib/fty/fty-sensor-env/composite-metrics -> ../../bios/composite-metrics` which is not what we need (we need an accessible `/var/lib/fty/fty-sensor-env/agent_th` file in the end).
Solution: in preinstallimage-bios.sh, create sensor-env symlink just for a legacy file location, new dir is made by packaging
=> Problem: symlink for fty-sensor-env data created incorrectly

obs/preinstallimage-bios.sh
Solution: dyop udr legacy path, it's no longer used by 42ity components
=> Problem: can't get a list of alert rules

obs/preinstallimage-bios.sh, setup/20-fty-compat.sh
Solution: push towards generation of FTY pathnames for /var/lib/fty via tmpfiles, and IFF an old system is being updated - relocate (and rename) its data from /var/lib/bios to /var/lib/fty.
=> Problem: prepackaged symlinks for legacy BIOS support make a mess

tools/db-init.in
Solution: let bios-db-rw is 'readable' by www-data group
=> Problem: REST API tests fails

tools/db-init.in
Solution: call it on correct directory
=> Problem: typo in chgrp

Makefile.am
=> Problem: fty-db-upgrade runs during first boot

Makefile.am, obs/preinstallimage-bios.sh
Solution: make sure all fty-db-*, mysql is DISABLED from the start
=> Problem: db created after startup

Makefile.am
Solution: disable the full unit name in preset file
=> Problem: db created on a first boot

Makefile.am, obs/preinstallimage-bios.sh, systemd/fty-db-firstboot.service.in, systemd/fty-db-init.service.in, tools/start-db-services
Solution: ... because fty-db-init is pullet via bios-db-init Requires.
Drop fty-db-upgrade (it never made a sense as db-init script do both).
Add fty-db-firstboot, which runs only if db was not initialized and
remains disabled by default. And disable bios-db-init too.
=> Problem: DB is still created during boot

tools/systemctl
Solution: add fty-db-firstboot to the wrapper
=> Problem: TestLicense fails

obs/preinstallimage-bios.sh, tools/start-db-services.in
Solution: mask it, so it won't be started under ANY circumstances.
start-db-service called by license acceptance will unmask and enable it.
=> Problem: DB is still started on first boot

tools/start-db-services.in, tools/systemctl
Solution: now that we have usecases for these methods, allow to use them against our units
=> Problem: our systemctl wrapper does not allow mask/unmask

.gitignore, Makefile.am, obs/preinstallimage-bios.sh, systemd/fty-tntnet@.service.in, systemd/ipc-meta-setup.service.in, tools/systemctl
Solution: name fty-core version differently and override during OS image generation
=> Problem: a tntnet@.service is also delivered by tntnet package

tools/db-init.in
db-init.in : use proper varnames for paths; fix whitespace; comment what and why we do by these www-data access rights
=> Problem: recent changes in db-init are not clear

setup/10-avahi-lxc.sh, systemd/ipc-meta-setup.service.in
Solution: rewrite its config before it starts, to block limitation of number of processes for its UID
=> Problem: avahi-daemon does not start in containers

Makefile.am
Solution: mention it in Makefile :)
=> Problem: 10-avahi-lxc.sh not installed into OS

tools/fty-route
Solution: when auto-sudoing, call "$0" "$@" not just "$@"
=> Problem: can not run "fty-route list" as admin

tools/fty-route
Solution: put them to iface[2], the first after lo
=> Problem: routes added to lo

tools/fty-route
Solution: allow "fty-route list -n" to avoid DNS resolution delays
=> Problem: fty-route does not list numeric data

setup/20-fty-compat.sh
Solution: convert the file to new agent's liking
=> Problem: upon upgrade from MVP, fty-email config is not preserved

tools/systemctl
Solution: fix typo in service name
=> Problem: fty-nut-configurator not manageable by wrapper

systemd/fty-tntnet@.service.in, systemd/wd_keepalive@.service, tools/loghost-rsyslog
Solution: tmpfiles is a different big system issue; we want the HW watchdog to run - so make no hard dependency
=> Problem: HW watchdog does not start if tmpfiles failed

setup/15-dpkg-database.everytime.sh
Solution: improve sanity checks and variable usage
=> Problem: 15-dpkg-database.everytime.sh reports double-slashes in pathnames

setup/15-dpkg-database.everytime.sh
Solution: add a final sanity check - that we do still have the metadata in live system
=> Problem: 15-dpkg-database.everytime.sh has potential to break the system

tools/systemctl
Update the filter of services that our wrapper allows to manipulate.
=> systemctl : support fty-discovery and fty-sensor-gpio

setup/20-fty-compat.sh
Solution: migration helper for https://github.com/42ity/fty-sensor-env/pull/24
=> Problem: fty-sensor still uses old naming convention

tools/diagnostic-information
Solution: Use -L instead of -H
=> Problem: Diagnostic script must always follow symlinks

tools/_bios-script.sh
Solution: strengthen password generation so it is accepted by security filters
=> Problem: first startup of tntnet fails

obs/preinstallimage-bios.sh
These are marked as `|| true` so should not break build of images without this feature.
=> preinstallimage-bios.sh : add optional support for more IPC LCD actions

tools/update-rc3
Solution: support respin numbers separated by either "plus" or "minus" characters nowadays, so "+9" is no longer "newer" than "+51" ;)
=> Problem: update-rc3 sorts respins wrongly

Makefile.am, setup/20-ipc-lcd-services.sh
Solution: add an ipc-meta-setup snippet to handle new services
=> Problem: new IPC LCD services not enabled on upgrade

tests/CI/ci-reset-virtual-machine.sh
Solution: manipulate resolv.conf et al inside chroot of prepared container (absolute links to host objects are meaningless or dangerous)
=> Problem: recent DNS commits broke ci-reset-virtual-machine.sh

tests/CI/ci-reset-virtual-machine.sh
Solution: in ci-reset-virtual-machine.sh add an ELEVATE_USERS list to pre-set sudoers for all privileges (can be defined via container's config file)
=> Problem: developer in LXC container wants root

systemd/bios.service, systemd/fty-db-engine.service.in, systemd/fty-db-init.service.in, systemd/fty-license-accepted.service
Solution:
* fix stop-start dependencies of `fty-license-accepted`, `fty-db-engine`, `fty-db-init` and its consumers to happen automagically, as services are stopped nicely or daemons are killed off
* mark availability of database in usable state with a touch-file `/var/run/fty-db-ready` that scripts and programs can `stat()` easily
* fix `systemctl stop (or restart) bios` to rule them all
On a side note, found that `amqp` and `mdns` services tend to freeze during stop quite regularly. Probably they share some pathology with `gpio`, and while a quick hack of `TERM, wait, KILL` might help, the real fix should be in code. Other services usually manage to stop without freezing :)
=> Problem: our systemd units need improvements

tools/db-init.in
This should simplify testing with deletion of database and credentials
=> db-init.in : manage files under /var/lib/fty whenever possible

systemd/biostimer-warranty-metric.service.in, systemd/fty-db-init.service.in, systemd/fty-tntnet@.service.in, tools/db-init.in
Solutions:
* make sure db-init syncs before it is done
* make DB credentials a required EnvironmentFile for all units except tntnet@bios
* restore bios-db-init alias just I case
=> Problem: DB consumers can start without credentials

Makefile.am, systemd/fty-core.conf
Solution: use tmpfiles to set up this directory too
=> Problem: /var/lib/fty recreated with wrong rights, if destroyed

obs/preinstallimage-bios.sh
Solution: Put the feature back into default config, so nut-scanner uses the DMF mode, and also matches the driver it ultimately suggests (default snmp-ups being the dmf version in this OS image)
=> Problem: BIOS_NUT_USE_DMF not anymore in devel images

tools/start-db-services.in
Context: If we take time to accept the license, and do so after systemd no longer tries to start units with failed dependencies/prerequisites (like fty-license-accepted), then enabling direct consumers of the database in start-db-services script does not enable units which in turn require these consumers.
Solution: Dig into our units to find the whole tree of units that rely on database, directly or indirectly, and start them after database initialization has completed. Also tell all components of bios.target to start.
=> Problem: grandchildren of DB are not started

tools/start-db-services.in
Solution: fix start-db-services script to match the wrapper's unfortunate expectations
=> Problem: our systemctl wants --no-block at the end of CLI

tools/start-db-services.in
Solution: do not enable both via start-db-services script... Now, why won't it also ignore these errors as explicitly told via "||"?..
=> Problem: tntnet@bios conflicts with its own alias

.gitignore, Makefile.am, obs/preinstallimage-bios.sh, systemd/fty-tntnet@.service.in, systemd/ipc-meta-setup.service.in, tools/envvars-ExecStartPre.sh.in, tools/systemctl, tools/tntnet-ExecStartPre.sh.in
Solution: separate the script to generate the envvar file into a separate script and service from tntnet-ExecStartPre.sh.in
=> Problem: have many uses for fty-envvars

database/mysql/0011_default_rc.sql
Solution: Prepared parent id=1 for rackcontroller-0. Datacenter should be created with id=1.
=> Problem: rackcontroller-0 isn't member of the structure causing many calls to fail

database/mysql/0011_default_rc.sql, tools/rc-bios-ci-container-delayedstart
Solution: support required goals:
* no changes if a 'rackcontroller-0' already exists in DB (e.g. during update)
* if one or more "rack controller" assets already exist (and none with a 'rackcontroller-0' db-name), pick the "myself" rack controller in a configurable manner (currently - one with lowest ID number; support using a different logic for later releases without changing this SQL file) and replace its db-name
* only if no "rack controller" assets already exist, create one with the following features:
** parented and powered by the first datacenter (if at least one is present) or un-parented (NULL) and "powered" by itself otherwise
** mark this asset as active
** set priority, user-name, ip, unit size and location to some valid values, not-readonly (can get modified)
** mark the …
=> Problem: 'rackcontroller-0' is just INSERTed no matter what

database/mysql/0011_default_rc.sql, systemd/fty-db-engine.service.in
Solution: jump through a few more hoops 0011_default_rc.sql::select_RC_myself() to ignore defined higher-priority attributes when looking at lower-priority attrs.
Thanks to validation for noticing the logical weakness even before the test matrix was fully defined.
=> Problem: search for "myself" did not avoid not-matched known attrs

systemd/fty-db-engine.service.in
Solution: apply missed commits to facilitate its self-check
=> Problem: fty-db-engine startup fails

database/mysql/0011_default_rc.sql, tools/envvars-ExecStartPre.sh.in
Solution: beside a list of all IP addresses of the current system, provide lists of just IPv4 and just IPv6 addresses, and use those to initialize data about rack controller in extattrs `ip.X` (v4) and `ipv6.X`. Just in case, while looking for an existing "myself", match all address types in both attributes.
=> Problem: during SQL init, IPv6 addresses of RC0 land into ip.X extattrs

systemd/fty-db-init.service.in, tools/start-db-services.in
Solution: after some looking at logs, the hundreds of looped calls to `systemctl` (making sure all DB dependants are started, even when systemd does not do its job right) amounted to a large overhead. Since we can instead pass many arguments to one call, do so by default on ARM. Startup cut from ~4min to 1m20s, including 1m5s of DB files and schema creation and initialization.
=> Problem: License acceptance slowed down in recent iterations

obs/preinstallimage-bios.sh
Solution: preinstallimage-bios.sh : try "usermod -G" as everywhere else instead of adduser
=> Problem: "bios" user not in "gpio" group

Makefile.am, obs/preinstallimage-bios.sh, setup/10-bios-gpio.sh, tools/init-os-accounts.sh
Solution: add a setup/10-bios-gpio.sh scriptlet for ipc-meta-setup to take care of this on boot; this would also help upgrades
See caveats in #187 - not an issue for our current focus, but can become one when we expand
=> Problem: bios user still is not in gpio group

Makefile.am, setup/90-nut-ownership.everytime.sh
Solution: as a quick hotfix, always apply proper ownership to NUT configs and runtime files
=> Problem: OS images generate different GIDs and NUT complains

tests/CI/ci-reset-virtual-machine.sh
Solution : ci-reset-virtual-machine.sh : deprecate "rootfs" as the directory for read-only roots in overlayfs mode; use a new "overlays-ro" dir instead.
=> Problem : ci-reset-virtual-machine.sh creates RO overlay roots under "rootfs" dir

tests/CI/ci-reset-virtual-machine.sh
ci-reset-virtual-machine.sh : add support for "--no-delete" mode so a VM may be updated or rebooted while keeping its data; add CLI aliases to halt, wipe and reboot a container
Note this is intended for developers who know why and when they are doing this - for example, if this option is used on an older container that had custom users/groups imported, it would not see newer definitions from a current release - the files present in overlayfs RW directory always win.
=> Problem: ci-reset-virtual-machine.sh always wipes container contents

tools/update-rc3
FYI for most reviewers: now when you download an OS image which is not some straight-forward upgrade (same image type and release as before, just with a newer timestamp and maybe alphabetic order) - e.g. when you change image types with `-U`, downgrade, etc. - you can now use a `-FF` argument (or `-FFo` for specifically OS images) to have the script set the `.forceflash` flag for this image candidate, and it will be preferred over anything after reboot (if it passes sanity checks of course, and if the `uImage` active on the IPC also has the forceflash flag support -- yesterday's build or newer).
To clear all existing forceflash flags before checking or downloading images, you can run the script with `-NFF` argument.
For more details, see the updated help (`usage()`) and the code :)
=> Add Forceflash support to update-rc3

tests/CI/ci-reset-virtual-machine.sh, tests/CI/ci-setup-test-machine.sh, tests/CI/jenkins-reset-virtuals.groovy, tests/CI/resetdb-bios-rc-demo.sh, tests/CI/update_demo
* Better support recent "no-delete" mode (update/reboot) with "devel" image containers
* Fail package customization script upon packaging system errors, to propagate issues to the caller
* In factory-reset-live, try more ways to reset user password to the simple default
=> Fixes for container-management scripts and "live factory reset"

tests/CI/ci-reset-virtual-machine.sh, tests/CI/ci-setup-test-machine.sh, tools/factory-reset-live.sh.in
* factory-reset-live can do a better job resetting NUT, DB and Password aspects
* container management failure-handling revised; automate preinstallation of Java if requested (for Jenkins agents, CLI tools of some 3rd-party projects), libzmq4-dev (to explicitly build e.g. malamute), and better cooperate with Jenkins as its agent - largely to eventually supplant the less featured (and insufficient for current needs) script used in CI to deploy build agents, as well as to have equivalent features on developer workstations already
=> Further fixes for container-management scripts and "live factory reset"

systemd/fty-license-accepted.path
fty-license-accepted.path : add explicit dependency for fty-db-* services for better protection from older systemd quirks
=> Problem: database sometimes fires up when it should not (EULA not yet accepted)

docs/examples/rsyslog.d/10-ipc.conf.in, tools/loghost-rsyslog
Now tested (on container) and works for tcp/udp on different target ports.
New feature -- `loghost-rsyslog --tcp --port 12345 --set-loghost 10.11.12.13 --toggle-rsyslog all` would cause the 42ity environment to log everything to the specified sink which can be a log server or just a `while : do nc -l 12345 ; done > file.log` one-liner. Note this is not required in our main lab appliances, they log to common sink already.
=> Allow setting loghost url to non-standard proto and port

obs/preinstallimage-bios.sh
Solution: expand the prefix of units searched for autoenable in OS images
=> Problem: etn/ipm/ipc services not autoenabled

obs/preinstallimage-bios.sh, tools/systemctl
Follows up on fallout from #217 "Problem: etn/ipm/ipc services not autoenabled"
Who thought that it is a good idea - returning in `systemctl list-unit-files` (*files* Carl!) a unit's alias that has no corresponding same-named file and so can not be `enable`d? ;)
=> Problem: systemd strikes again

obs/preinstallimage-bios.sh, tools/systemctl
After all the magical neat error handling in PRs #217 and #219, we see this during build:
````
[  306s] + for unit in '$(/bin/systemctl list-unit-files | egrep '\''^(fty|etn|ipc|ipm|ova)-*'\'' | cut -d '\'' '\'' -f 1)'
[  306s] ++ /bin/systemctl show -p Id ipc-lcd-engine.service
[  306s] ++ sed 's,^Id=,,'
[  306s] Running in chroot, ignoring request.
[  306s] + unit_realname=
[  306s] + '[' -n '' ']'
[  306s] + unit_realname=ipc-lcd-engine.service
[  306s] + /bin/systemctl enable ipc-lcd-engine.service
[  306s] Operation failed: No such file or directory
[  306s] + exit 1
````
=> Preinstall: Running in chroot, ignoring request

obs/preinstallimage-bios.sh
Solution: rename the tntnet configuration snippet file, so it
is not compiled into bios.xml and does not cause overheads by
loading the shared library file. This is still reversable in
particular deployments of the OS image, if needed.
=> Problem: REST API for disabled services still active

obs/preinstallimage-bios.sh
Solution: Support zproject-ized fty-rest deliverables via symlinks to old known paths in resulting image
=> Problem: /usr/*/fty-rest unknown to others

obs/preinstallimage-bios.sh
The accounts must be stable across image versions, otherwise upgrades
would break. To document this and to avoid accidental breakage when
reshuffling the code, add an explicit -u <UID> option to each useradd
call, like we already do when creating the groups.
=> preinstallimage-bios.sh: Explicitly set IDs for the user accounts

docs/examples/pam.d/fty
Problem : with "auth   required        pam_unix.so try_first_pass", pam_authenticate() API function failed.
Note with or without "auth   required        pam_unix.so try_first_pass" SASL demon is still working.
BTW, what was the intention to have try_first_pass argument directive at this level, just after pam_env (I mean) ? I'm have some doubts about the efficiency of it.
Solution : so remove it. 
=> Problem: pam_authenticate API is failing

Makefile.am, setup/16-machineid-dir.everytime.sh
Solution: Add an ipc-meta-setup snippet to provision and make sure it exists on every boot.
=> Problem: No persistent directory for machine unique data

obs/preinstallimage-bios.sh.in
Solution : wait /usr/share/bios folder moved in /usr/share/fty before copying ftylog.cfg
=> Problem : ftylog.d is packaged in /usr/share/bios/examples/config

Makefile.am, configure.ac, obs/preinstallimage-bios.sh.in, setup/17-proxy-file.everytime.sh, systemd/fty-proxy.path.in, systemd/fty-proxy.service.in, systemd/fty-tntnet@.service.in, systemd/ipc-meta-setup.service.in
Solution: prepare an /etc/default/fty-proxy with presumably sufficient access rights
=> Problem: no place for a proxy settings file

tools/disable-root-account, tools/enable-root-account
Solution:
* Use a standard loop to process the CLI arguments
* Quote usage of variables
* Add a usage()
* Add an uncommentable line to report the password value (usable in QA lab)
* Try to protect from someone hijacking the password file by removing it (if present) right before the echo of the value
=> Problem: (en|dis)able-root has no help and clumsy CLI processing

database/mysql/0014_user_preferences.sql, database/mysql/Makefile.am
Alternative (and much simpler) fix for https://github.com/42ity/fty-rest/pull/466. Give default preferences to builtin users so that the proprietary endpoint always has something to return.
=> [DO NOT MERGE] Set default infos for builtin agents

tools/factory-reset-live.sh.in
Solution: restart that service to reapply things, hope for the best :)
=> Problem: factory-reset-live does not recreate ipc-meta-setup

database/mysql/0014_user_preferences.sql
=> Problem: db-init fails after reboot because of incosistence in DB

tools/tntnet-ExecStartPre.sh.in
Certainly, keeping using `root` is wrong here.
=> tntnet-ExecStartPre.sh.in : set HOME and USER according to run-time webserver account

tools/envvars-ExecStartPre.sh.in
Avoid duplicate space-separated domain names (from default and resolv) in `ENV_KNOWNDOMAINS` and subsequently bogus value(s) in `ENV_KNOWNFQDNS`.
WAS:
````
ENV_KNOWNDOMAINS='lab.xxx.com lab.xxx.com'
ENV_KNOWNFQDNS='jenkins2-rc3.lab.xxx.com,jenkins2-rc3.lab.xxx.com lab.xxx.com'
````
NOW:
````
ENV_KNOWNDOMAINS='lab.xxx.com'
ENV_KNOWNFQDNS='jenkins2-rc3.lab.xxx.com'
````
=> Fix domain processing in envvars-ExecStartPre.sh.in

tools/verify-fs.in
This fixes a warning from the verify-fs on the OVA about the /lib/modules directory:
`Jun 29 12:48:51 eaton-rc-005056B19DB0 verify-fs[12602]: /run/initramfs/mnt/root-rw/overlay/lib contains suspicious files.`
=> verify-fs fixes

obs/preinstallimage-bios.sh.in
This will make the SSH server sensitive to the FTY pam_tally2.so
configutation, to prevent locked out users from accessing the system
through SSH.
This will have an effect only if the account lockout is enabled (which
is not by default) and will not affect public key authentication.
=> Add fty-auth layer to sshd PAM config

obs/preinstallimage-bios.sh.in
This will make the SSH server sensitive to the FTY pam_tally2.so
configutation, to prevent locked out users from accessing the system
through SSH.
This will have an effect only if the account lockout is enabled (which
is not by default) and will not affect public key authentication.
=> Add fty-auth layer to sshd PAM config (1.4)

Makefile.am, docs/examples/sudoers.d/fty_00_base.in, tools/runas-_bios-script
This utility allows tntnet to spawn commands as `_bios-script`. This is intended for running user scripts provided by fty-scripts-rest and maybe other components in the future.
Precautions were taken to prevent string injection attacks, but this is a safe design only as far as user priviledges go. A more thorough sandboxing scheme would require the usage of Linux namespaces/cgroups/ulimits, but this should be good enough as a first approximation to be eventually refined later.
=> Implement runas-_bios-script utility

.gitignore, Makefile.am, configure.ac, docs/examples/Makefile.am, docs/examples/nut-server.service.d/configure-nut-users.conf.in, tools/setup-nut-users-ExecStartPre.sh, tools/setup-nut-users-ExecStartPre.sh.in
Also create an environment file for all clients to get credentials (currently `fty-nut-command`).
=> Create NUT internal users on nut-server start

docs/examples/nut-server.service.d/configure-nut-users.conf.in
Helper script got installed at a location I did not expect. Adjust path.
=> Fixup configure-nut-users.conf ExecStartPre path

obs/preinstallimage-bios.sh.in, systemd/ipc-meta-setup.service.in
Problem : on heavy load activity, fty-nut stopping working after a while.
Solution : set unlimited High Water Mark on malamute clients side likes we have on the broker itself
In the detail.
on heavy load stress two Threads (3 & 4) are stucked. They are waiting forever on zmq::mailbox_t::recv.
fty-nut creates one mlm client which both subscribe and consume on different STREAM. One Thread (3) is trying to inform the application that some ASSET has been published in STREAM ASSET, and the other Thread (4) is trying to publish metrics in loop.
~~~~
"STREAM SEND"+----------+ "STREAM DELIVER"    
mlm_client_send()----------->| msgpipe  |<-------------pass_stream_message_to_app()
Thread4:producer             +----------+              Thread 3:consumer
~~~~
For more detail information, look at …
=> Problem : default HWM value may block fty-agents under stress load

tools/update-rc3.in
Solution: Do it, along with updating upon image deletion
Also error out on missing package manifest, now that these are produced by CI
Note that upon successfull image download, activation request is also set to
the new image (using its index), for completion of the SW upgrade
=> Problem: New images should be listed in SW manifest

obs/preinstallimage-bios.sh.in, tools/tntnet-ExecStartPre.sh.in
Solution: list the filenames (and order) we expect in the sanity checker.
Avoid conflicts with components that could deliver filenames under numbered
patterns we already use.
Also ensure tntnet-ExecStartPre.sh uses the same order of filename listing.
Thanks: Gerald Guillaume <GeraldGuillaume@eaton.com> for finding the bug cause
=> Problem: bios.xml sanity check is lax enough to fail

obs/preinstallimage-bios.sh.in
Since we store the original journals in a memory filesystem, sync them to disk every second. The default of 5min delays our debug investigations and *seems* to botch some recording of timestamps.
NOTE: There is a small risk of this option increasing the load from `journald`, especially on systems with enabled debugging (and more messages to log), so CCing everybody I could find just to give a heads-up :)
=> Journald sync

tests/CI/ci-reset-virtual-machine.profile
Solution: Port and document the shell-profile functions already
in use on some workstations, so others can benefit.
=> Problem: Not easy for devs to manage their local 42ITy containers

tools/enable-root-account
Prevents issue when `enable-root-account` unintentionally spawns long-running processes, interfering with SystemD unit shutdown detection when running it inside a service.
=> Run disable-root-account in another cgroup

tools/enable-root-account
Prevents issue when `enable-root-account` unintentionally spawns long-running processes, interfering with SystemD unit shutdown detection when running it inside a service.
Backport of #324 for 1.5.0.
=> Run disable-root-account in another cgroup (1.5.0)

tools/udhcpc-hook.sh
My hypothesis is that sometime the "$reason" does not belong to the list bound|renew|BOUND|RENEW|REBIND|REBOOT, so we failed in the default case which return, so we lost the chance to initialize properly the hostname.
Solution, do not take in account the "$raeson" to force the hostname initialization happening in every cases.
=> Problem : OVA image sometime register its hostname to default localhost to the DHCP srv

tools/diagnostic-information
Solution: Add licensing information to the report
=> Problem: Diagnostic is missing licensing information

obs/preinstallimage-bios.sh.in, setup/20-ipc-lcd-services.sh, tests/CI/ci-reset-virtual-machine.sh, tools/ifplug-dhcp-autoconf.sh
Solution: old one did not fail... they were missing - they were disabled.
Pepper the code with "||true" tails.
=> Problem: new systemctl fails to disable nonexistent units

tools/diagnostic-information
Solution:
* diagnostic-information : csv_export() : stderr'ors of the export should be saved nearby in an `export.err` file
Note: this commit does not directly address having `bios-csv` tool print its logs onto `stderr` rather than `stdout` as it seems to do now. Such fix belongs there.
=> Problem: bios-csv error log saved right into CSV file

tools/update-rc3.in
*    update-rc3.in : do not claim having downloaded an image when ACTION_DOWNLOAD_OSIMAGE=no
*    update-rc3.in : when touching FR or erase-all, differentiate ACTION_DOWNLOAD_OSIMAGE=no vs successful download in messages
*    update-rc3.in : when not downloading OS images, default to ACTION_REMOVEOLD_OSIMAGE=no
These bit me during today's revision of our misbehaving devices.
=> Fix a few bugs in update-rc3

tools/disable-root-account, tools/enable-root-account
These changes should ease application and use of "CI Hacks" that simplify test deployments a lot, while not impacting the end-user systems "as is".
=> enable-root-account improvements for CI automation

tools/generate-release-details.sh
This should revive `/etc/release-details` (non-JSON) file and `/etc/bios-release*` symlinks.
=> generate-release-details.sh : quoting fixes including one severe

tools/systemctl
Solution: removed fty-alert-flexible reference as it should be removed
=> Problem: fty-alert-flexible referenced when it should be removed

Makefile.am, configure.ac, obs/preinstallimage-bios.sh.in, systemd/fty-hostname-setup.service.in, tools/fty-hostname-setup, tools/udhcpc-hook.sh, tools/udhcpc-override.sh
This change set evicts our product-intimate host name setup into a separate script and service, so this should not confuse the DHCP client requesting and receiving a bogus hostname (if a reasonable one was not set for some reason by the OS loader).
=> FTY hostname setup and other DHCP client fixes

systemd/fty-db-engine.service.in
* fty-db-engine.service.in : add both belt and suspenders, check for EULA file here directly also
* fty-db-engine.service.in : do not abort DB startup right when told to
These fixes are not quite tested (staged also into `featureimage/tntnet-crash` for more live experience) but should help avoid the intermittent issues we had with database starting and stopping rapidly (and uncleanly) during CI testbed preparation.
=> Fallback robustness in fty-db-engine.service.in

systemd/fty-db-engine.service.in
…wrap into shell to let it figure this out better
Thanks to @kkathreen for noticing and alarming.
=> fty-db-engine.service.in : our systems have /USR/bin/test... 

systemd/fty-db-engine.service.in
The somewhat more reliable version of database startup should help against some cases when systemd loses it.
=> Backport 2.0.0 dbstart

systemd/fty-db-init.service.in
Solution: disable systemd start timeouts so we do not
half-initialize and then be killed to restart with a
corrupted schema...
=> Problem: sometimes slow hosts take ages to fty-db-init (master)

systemd/fty-db-init.service.in
Solution: disable systemd start timeouts so we do not
half-initialize and then be killed to restart with a
corrupted schema...
=> Problem: sometimes slow hosts take ages to fty-db-init (2.0.0)

systemd/fty-db-init.service.in, tools/db-init.in
Solution: Move the touching into the script (optional, to let devs
still use it safely) and let the service still define the path used
=> Problem: Not sure if fty-db-ready appears at right moment

tools/db-init.in
Mostly commenting the unclear/forgotten logical points while investigating the script's behavior in case we cosmetically edited SQL files (and kept the version tags) for a newer release. 
Long story short: if the tag was imported earlier, the file will not be reprocessed; if the version tag got changed, the script will complain and die; so any editions in a re-release may happen only for cosmetic purposes and should not actually change the schema compared to an older release of this SQL file name: in case of upgrades, either the change will not be seen (if version is unmodified), or would abort the fty-db-init.service (if version is modified). Any such schema changes must arrive in subsequent (alphabetically) filenames with payload set in stone after an end-user release.
There is a couple …
=> Revise db-init script

obs/preinstallimage-bios.sh.in
For an unknown reason, this SystemD unit blocks our ecosystem jobs from starting. Work around it by masking this unit.
This is not a proper fix as the real root cause has not been identified.
=> Mask systemd-time-wait-sync.service

systemd/fty-tntnet@.service.in, tools/tntnet-ExecStartPre.sh.in
- syscall setresuid fails on Debian 10, preventing login
- temporary fix is to run tntnet as root (only for Debian 10 image)
Signed-off-by: Mauro Guerrera
<mauroguerrera@eaton.com>
=> [DNMY] Proposed workaround for PQSWPRG-7176

ci_deploy.sh, tests/CI/ci-reset-virtual-machine.sh, tools/generate-release-details.sh, tools/update-rc3.in, tools/verify-fs.in
As elsewhere, these changes extend original support for accompanying `\*.md5` files with addition of `\*.sha256` and `\*.cksum` files (the latter far from secure, but adding easy to verify content length check, unlike the first two... and yet another algorithm to fool simultaneously in case of malicious intrusion).
=> Update support of different checksums in fty-core scripts

Jenkinsfile, setup/ipc-meta-setup.sh, systemd/ipc-meta-setup.service.in
A somewhat less intrusive backport of #392 to 2.1.0 release:
* did not add `date -u` timestamping
* did not add recognition or workaround of scriptlets not marked executable in the filesystem (so such errors in component development would fail the `ipc-meta-setup.service` as they did before)
=> Alleviate ipc-meta-setup timeouts and make them more debuggable (2.1.0)

setup/ipc-meta-setup.sh, systemd/ipc-meta-setup.service.in
While the likely root cause of failures seen in tests was the load on hypervisor or NAS backing the test VMs, to the point that probably ipc-meta-setup was killed by systemd (some other services including the journal were, due to lack of logs the guess is inconclusive however), we can try to tackle it by:
* bumping the systemd timeout (discussed to not make it infinite at this time);
* improving logging for death by certain signals;
* improving logging of progress (began/finished some steps) to simplify postmortems.
=> Alleviate ipc-meta-setup timeouts and make them more debuggable

setup/ipc-meta-setup.sh, systemd/ipc-meta-setup.service.in
Replay the botch of #393 wrongly targeted
=> Alleviate ipc-meta-setup timeouts and make them more debuggable (really to 2.1.0)

tools/ssl-create.sh
- set CA:FALSE
- extend expiration date to 9125 days
=> Update SSL certificate generation for tntnet (remove CA:TRUE)

obs/preinstallimage-bios.sh.in
the fty-license-accepted Requirement on multi-user.target
(cherry picked from commit beec9193915bd8ac029faa0a5341c89052ad5ddf)
=> Remove nut.target from multi-user.target, to avoid breaking

systemd/fty-core.conf, tools/ssl-create.sh
- remove CA
- extend validity to 25 years
Backport of #397 - also would need a backported copy of https://github.com/42ity/fty-core/pull/402/commits/430441b0700f80bede0a610c23d7dee2c1b8ce28 to work in OS image
=> Update SSL certificate generation for tntnet (remove CA:TRUE) (2.1.0)

systemd/fty-license-accepted.service
Analysis: After recent dependency changes, the listing of
dependent units to start came up empty where we want to tickle
them to start up, and so systemctl errored out and then
fty-license-accepted.service stopped soon after starting.
As a result, units that (newly) declared they are PartOf
fty-license-accepted.service, like fty-db-engine, were stopped.
Solutions:
* add RequisiteOf for completeness
* cache the list of found units into a variable, and only
call systemctl if the list is not empty, or visibly log
otherwise (a bit of future-proofness).
TODO: port this approach to other units that stop/start stuff
One idea was to also add "-p ConsistsOf" into the query of
services to tickle, but this is not semantically correct
for causing start-ups.
Signed-off-by: Jim Klimov …
=> Problem: fty-license-accepted.service fails to ExecStartPost

obs/debian.copyright, setup/20-th-names.sh.in, tools/JSON.sh, tools/disable-root-account, tools/enable-root-account, tools/envvars-ExecStartPre.sh.in, tools/verify-fs.in
Note: Actually at some point should drop the copy in fty-core and use directly https://github.com/42ity/JSON.sh/tree/FTY - over time it became good enough to package and track separately as a portable (multi-shell syntax) and very much testable codebase.
=> Shell JSON queries simplified with bits from main project

systemd/fty-license-accepted.service
Analysis: After recent dependency changes, the listing of
dependent units to start came up empty where we want to tickle
them to start up, and so systemctl errored out and then
fty-license-accepted.service stopped soon after starting.
As a result, units that (newly) declared they are PartOf
fty-license-accepted.service, like fty-db-engine, were stopped.
Solutions:
* add RequisiteOf for completeness
* cache the list of found units into a variable, and only
call systemctl if the list is not empty, or visibly log
otherwise (a bit of future-proofness).
TODO: port this approach to other units that stop/start stuff
One idea was to also add "-p ConsistsOf" into the query of
services to tickle, but this is not semantically correct
for causing start-ups.
Signed-off-by: Jim Klimov …
=> Problem: fty-license-accepted.service fails to ExecStartPost (2.1.0)

systemd/fty-db-engine.service.in, tools/start-db-services.in
Educated guess from reading the systemd journal:
After EULA acceptance, the database did not come up, so the wizard errored out. It seems that the scripted processing got caught into the time range between the regular systemd retries to start fty-db-engine, so that a copy was running started before the script that eventually found in its ExecStartPre the license file to not exist at that moment, and another copy "started" (or rather "told to start" due to systemd properly avoiding running several copies of the same service instance) by virtue of having fty-license-accepted.service finally active, and another by the explicit fallback start in the script.
In the end, systemctl called from the script probably returns the failure to start which originated from the service instance startup …
=> Hotfix DB service startup occasionally failing after EULA

.gitignore, Makefile.am, configure.ac, systemd/fty-db-engine-pre.service.in, systemd/fty-db-engine.service.in
=> Introduce fty-db-engine-pre to offload killing of competing mysql implementation instances (2.1.0)

.gitignore, Makefile.am, configure.ac, systemd/fty-db-engine-pre.service.in, systemd/fty-db-engine.service.in
More arcane systemd magic to combat issues that should not exist in the first place.
Per internal discussion:
The symptoms I have accumulated so far is that we have some units, including fty-db-engine.service and fty-license-accepted.service (and wrapper bios/ipm2/… services for same-named targets) that manipulate other unit states via systemd in their ExecStartPre lines. Sometimes, when systemd processes this unit’s startup, it just loops executing this line endlessly, and nothing seems to be able to kill this “activating” unit except a “reboot -f”. But this is the service definition we had for years and never saw (or noticed?) such issues, until very recently, so maybe something came in through recent upstream Debian changes. I’ve also asked on systemd IRC, and they confirmed that units …
=> Introduce fty-db-engine-pre to offload killing of competing mysql implementation instances

tools/update-rc3.in
From the beginning update-rc3 can use a latest build from the original directory for the current OS image type, this is what it was made for. Later added `-U URL` support only allowed the complete URL to OS image file, possibly of another type than currently deployed, primarily for CI farm and developer workstation VMs.
This PR marries the two features, to process `-U URL/` (ending with slash) as the custom base "HTTP-directory" in which to find a latest image by existing algorithm, to simplify development iterations.
=> Update-rc3 : extend -U to pull latest build from a custom directory

obs/preinstallimage-bios.sh.in
Unless something explodes, eligible for release backporting too
=> preinstallimage-bios.sh : reduce fty-shm-cli logging in deploy images

obs/preinstallimage-bios.sh.in
When generating the packages list, for the Legal Information display,
ensure that we match the current package, and not just one ending with
the same name, to avoid missing packages from the list
(cherry picked from commit a0fd3b9afc1f338b5a431c02137b22a73bbd1dd9)
=> Improve packages listing match and avoid missing packages

tools/verify-fs.in
As reviewed recently, we had a problem with verify-fs calling `log()` before it knew where to send the reports (stderr or syslog via `logger`).
This PR fixes that, and also adds a summary report (to both of these log targets) that the inspection ran and whether it found any mismatches.
Finally, if some were found, it (newly) exits with an error, failing the service unit visibly.
=> Verify-fs fixes (master)

docs/examples/rsyslog.d/10-ipc.conf.in
Follows up from #427 to also store the messages from `verify-fs` into a newly defined `/var/log/verify-fs.log`
=> 10-ipc.conf.in : track an additional separate audit log for verify-fs runs

obs/preinstallimage-bios.sh.in
… on non-devel OS images (see #432 for master)
Dev-tested on latest release candidate (without the file it listens on `:::3306`, with the file it listens on `127.0.0.1:3306`)
@EatonEKia : I did not quickly pick a syntax to have it listen on both IPv4 and IPv6 localhosts. With multiple lines, the latest one is used; with comma-separated list of IPs the server does not start. So TODO for later... maybe not at all possible, per https://www.cyberciti.biz/faq/unix-linux-mysqld-server-bind-to-more-than-one-ip-address/
=> obs/preinstallimage-bios.sh.in : fix database to localhost… (2.1.0)

obs/preinstallimage-bios.sh.in
Limit SSH to Administrator user (i.e. no Viewers like "monitor")
=> Limit SSH to Administrator user (2.1.0)

obs/preinstallimage-bios.sh.in, systemd/bios-ssh-last-resort.service.in
These changes are still in testing on the feature image, so not part of the earlier big backport PR #439.
Without something like this in place, an SSH login (and logout) on port 22 breaks connectability on port 4222 as used by CI and fallback support.
=> Backport SSHD units fixes from featureimage/deb10

tools/update-rc3.in
[PQSW-284] update-rc3.in : modern etn-sw-update maintains /var/lib/fty/sw-update/activation_requested with the image number in manifest, we should not overwrite it with the exit-code
=> update-rc3: Do not overwrite /var/lib/fty/sw-update/activation_requested by exit-code

Makefile.am, setup/90-mylogin.everytime.sh, tools/db-init.in
After our system has initialized fty-db-init with a database password, subsequent starts of fty-db-engine log that they can not run that script full of helper tools. Same can be said for upgrades with older existing database and login into the newer images, so the reconciliation of that script with our setup is done both at startups via ipc-meta-setup and right after we've generated and tested a database password in fty-db-init.
=> Avoid failing /etc/mysql/debian-start from Debian-provided mariadb

systemd/biostimer-verify-fs.service.in, tools/verify-fs.in
Essentially, make sure syslog.service (pulled by syslog.socket and implemented for us by rsyslogd.service) is running before this script is.
If there was some error starting it, we have a major issue so there is no fallback to write into a log file directly and so avoid the CI errors (sometimes we do lack the log file to GET in CI - for normal circumstances of unmanage startup race, this PR should solve that; any remaining faults are still of interest).
=> Make sure the verify-fs reports early after boot do get logged

tools/update-rc3.in
At the time of posting, this is partially functional per intended design, but enough for MVP in the product practice.
The updated script can handle (apply, clean away) more currently supported naming patterns for the OVA loader file present in the recovery location, though currently it should be downloaded with `--url-...` argument or delivered by other means, which is the focus of remaining work in progress.
If the checksum file for uncompressed content of the ovaloader is available (not generated by the script if missing, at this time) then it can be compared to existing on-disk image to quickly skip flashing if already present there. This can be achieved by passing the base URL of the loader file (not `.gz`) for downloading; getting data and both checksums regardless of URL is another …
=> Update-rc3 enhancements related to ova loader

tools/update-rc3.in
Make `apply_rawfwimage_ovaloader()` more reliable if there are several loader related files and not all are good.
=> Update OVA loader fix for multiple files present

Makefile.am, setup/11-mount-boot-noauto.sh
Not-yet-tested scriptlet to (eventually) stop mounting /boot R/W if we ever did. See also #459.
=> Introduce setup/11-mount-boot-noauto.sh

Makefile.am, setup/11-mount-boot-noauto.sh, tools/update-rc3.in
Not-yet-tested follow-up to #458 to (eventually) stop mounting `/boot` R/W if we ever did.
=> Introduce setup/11-mount-boot-noauto.sh and Update OVA loader fix for multiple files present (2.1.0)

obs/preinstallimage-bios.sh.in
Oopsie-daisie...
Re-checked in an image with new fty-rest package deployed manually.
=> obs/preinstallimage-bios.sh.in: fix typo missed by reviews

tests/CI/cmpjson.sh, tests/CI/testlib.sh, tests/CI/weblib.sh, tools/JSON.sh, tools/envvars-ExecStartPre.sh.in, tools/systemctl
This reverts commit 1b8e2df86a5b4bc0f8f7abd299aadbfb200f5e0a - the probable issue was located and fixed elsewhere, and applies further fixes from upstream project. Tested in container with scripts that were broken after the previous backport iteration.
This change among other fixes makes the script more portable so it can be used to parse JSON data from loader and other non-bash shell interpreters, and to pretty-print in-vivo responses to `/usr/share/bios/scripts/restapi-request.sh` queries when troubleshooting.
=> Fix JSONSH_SOURCED detection for bash, and --get-string mode

docs/examples/sudoers.d/fty_00_base.in
Used by fty-srr-cmd, not the best way, but do the job quickly.
=> Adding test binary for bios users used to check password

systemd/fty-db-engine.service.in, tools/rcmysql-transient
Seems systemd still processes service stops (especially ones where an ExecStop, or a script called from one, calls `systemctl stop` for another) differently when the OS is shutting down vs. OS working and individual services "just" stopping for maintenance or to restart them. 
In case of OS shutdown, that systemctl client seems to lock up and does not tickle the other service in reality until the caller ends - which is a race. In case of usual living OS workflow, it just works flawlessly...
Since when knowingly shutting down we do not expect to restart services and dependencies in proper order during this ending uptime, we can forgo the wait for transient service stop from its wrapper and just let them both do what is needed to be done quickly. Note that the files being removed in "usual" …
=> [PQSWPRG-7529] fty-db-engine.service + rcmysql-transient: smoother processing of system shutdown (vs usual service stop/restart)

setup/20-th-names.sh.in
This was only supposed to run on revision 0... but did not specify of which hardware since there was no choice at the time :)
With container testing of Debian:Testing builds, the final line `udevadm trigger --subsystem-match=tty` fails due to R/O mounted `/sys` which was not a problem for Debian 10 and 8.
=> setup/20-th-names.sh.in: avoid confusing containers or OVAs

tools/envvars-ExecStartPre.sh.in
Tested in a container with eth1 dhcp-served:
````
jim@ipm2-devel:~/FTY/fty-core$ ps -ef | grep dhc
root     26609     1  0 09:10 ?        00:00:00 /bin/busybox udhcpc -i eth1
jim@ipm2-devel:~/FTY/fty-core$ grep dhcp /etc/network/interfaces  
iface eth1 inet dhcp
````
First run with the new script (image-provided did not have features from this PR) only adds the new lines, did not break content of earlier data:
````
jim@ipm2-devel:~/FTY/fty-core$ sudo tools/envvars-ExecStartPre.sh
Generate common run-time environment variables file for 42ity
Make sure the current OS image name and other details are populated into '/run/fty-envvars.env'...
A /run/fty-envvars.env already exists, we will see below if its content is obsolete or not
--- /run/fty-envvars.env	2021-05-25 09:10:47.668498951 +0000 …
```
=> tools/envvars-ExecStartPre.sh.in: report ENV_DHCP_CONFIG and ENV_DHCP_ACTIVE interface lists

tools/bios-networking, tools/ifupdown-force
On one hand, we have to disable the network interface when we deliberately `ifdown --force` it, because otherwise lingering DHCP clients and such tend to resurrect while we try to carefully restart networking. On another hand, our own tooling checks for disabled NICs with static addressing to avoid enabling administratively-down pre-configured back-up interfaces. Maybe this is why sometimes our testbeds end up without networking which is so easy to fix on console and neigh impossible remotely. Although they do use DHCP... in any case, bringing up the interface before configuring during the reconfig activity it should help.
=> tools/ifupdown-force and bios-networking: track link state more diligently

Makefile.am, configure.ac, systemd/fty-tntnet@.service.in, tools/ssl-ExecStartPre.sh.in, tools/tntnet-ExecStartPre.sh.in
As discussed earlier, this approach should allow different product bundlings with varied web server fronting the user interactions to have their HTTPS certs generated with the method defined by the product bundle, before the binary starts.
This dispatching script can pass args into the cert-generating script (e.g. the unit instance name), so eventually this little code can be an ExecStartPre for more than just the web HTTPS cert - but that would need evolution in the actual scripts doing the work to accept args and not hardcode "bios.pem" and is out of scope for this one :)
=> Offload certficate update scripts from tntnet-ExecStartPre

database/mysql/0024_batt_warranty_date.sql, database/mysql/Makefile.am
Change from "battery_warranty_expiration_date" to
"battery.end_warranty_date", for coherence and generic
handling of alert (later)
Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>
=> Update existing Ext attribute

tools/generate-release-details.sh.in
Since we did not move forward with #517 for a reason currently, leave a comment in the code to explain why.
=> generate-release-details.sh: comment to clarify the use of HWD_* values

Makefile.am, obs/preinstallimage-bios.sh.in, tools/compress-logs, tools/coredumper
This PR achieves several goals:
* task to let "admin" user read the core files (filter processes are a standard bypass to assign rights to sensitive data such as core files)
* (optional, currently on by default) summarize the core dump info (more with gdb present - e.g. on devel images) to help get a quick idea about the crash and its circumstances
* (optional, currently on by default) compress the core files to not DoS the system when processes crash
Script tested on brewing release OVA; full integration into OS image proposed but not yet tested by a squashfs build
=> Introduce the coredumper tool and use it in system config

tools/start-db-services.in, tools/systemctl
Currently the chain of events in our OS images only activates bios-target-watchdog.timer and .service units, as prodded by (re-)evaluation of the bios.service after fty-license-accepted becomes active, but not their equivalent for ipm2. This causes value-added units to not restart automagically after failures, at least not until the first reboot after passing the EULA wizard.
CONTEXT: In case of smaller-scale failures outside the direct required-dependency propagation, such as restart of malamute which does not cause a fault/stop of ipm2.target (nor bios.target), units that do depend on the failed service (e.g. fty-asset or etn-amqp) stop... and then there is no systemd event to cause their start-up: such units are WantedBy the respective target, and target remains running un-interrupted. …
=> [IPMPROG-2421] tools/systemctl + start-db-services: manage ipm2 + ipm2-target-watchdog
